# Generated by Django 5.1.4 on 2024-12-05 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_blog_date_blog_categories_blog_slug_and_more'),
        ('blog', '0013_alter_blog_blog_date'),
    ]

    operations = [
    ]
